[Hotspot]
# WiFi hotspot name  
hotspot_ssid=CubeSat
# WiFi hotspot password - note: this password is stored in the clear!
hotspot_password=amsat	
# Web Dashboard port number. If 80, no port needs to be entered in browser
dashboard_port=80
# Web terminal setting during hotspot - note, there is no authentication for this!
web_term_hotspot=yes 
# Web terminal setting during WiFi - note: there is no authentication for this!	
web_term_wifi=no 
