#!/bin/bash

echo -e "\nLog file script for CubeSatSim\n"

if [ "$1" = "-r" ]; then
  sudo journalctl -a -u rpitx > logr.txt 
  cat logr.txt
  echo -e "\nLog file also saved as /home/pi/CubeSatSim/logr.txt"
else
  sudo journalctl -a -u cubesatsim > log.txt 
  cat log.txt
  echo -e "\nLog file also saved as /home/pi/CubeSatSim/log.txt"
fi
