#!/bin/bash

echo -e "\nLog file script for CubeSatSim\n"

if [ "$1" = "-r" ]; then
  sudo journalctl -a -u rpitx > /home/pi/CubeSatSim/logr.txt 
  cat /home/pi/CubeSatSim/logr.txt
  echo -e "\nTransmit Log file also saved as /home/pi/CubeSatSim/logr.txt"
elif [ "$1" = "-c" ]; then
  sudo journalctl -a -u command > /home/pi/CubeSatSim/logc.txt 
  cat /home/pi/CubeSatSim/logc.txt
  echo -e "\nCommand and Control Log file also saved as /home/pi/CubeSatSim/logc.txt"
else
  sudo journalctl -a -u cubesatsim > /home/pi/CubeSatSim/log.txt 
  cat /home/pi/CubeSatSim/log.txt
  echo -e "\nLog file also saved as /home/pi/CubeSatSim/log.txt"
fi
