Attribute VB_Name = "Module1"
Sub Cleanup()
Attribute Cleanup.VB_Description = "Cleans up AFSK telemetry by deleting every other row.  Make sure the first row is the timestamp, not the telemetry data."
Attribute Cleanup.VB_ProcData.VB_Invoke_Func = "t\n14"
'
' Cleanup Macro
' Cleans up AFSK telemetry by deleting every other row.  Make sure the first row is the timestamp, not the telemetry data.
'

'
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Selection.Delete Shift:=xlUp
    ActiveCell.Offset(1, 0).Range("A1").Select
    Rows("1:1").Select
        
    End Sub
