showNavigation: false
additionalNavigationLinks:
  - title: CubeSatSim Wiki
    url: https://CubeSatSim.org/wiki
    target: _blank
  
  - title: CubeSatSim Code
    url: https://CubeSatSim.org/code
    target: _blank   

  - title: CubeSatSim YouTube Videos
    url: https://www.youtube.com/@ku2y
    target: _blank    

actions:
  - title: "Show CubeSatSim Config"
    shell: /home/pi/CubeSatSim/config
    icon: "&#9881;" # gear
    onclick: execution-dialog
    timeout: 5
    
  - title: "Change Mode to APRS"
    shell: /home/pi/CubeSatSim/config -a
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to FSK"
    shell: /home/pi/CubeSatSim/config -f
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to BPSK"
    shell: /home/pi/CubeSatSim/config -b
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to SSTV"
    shell: /home/pi/CubeSatSim/config -s
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to CW"
    shell: /home/pi/CubeSatSim/config -m
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to Repeater"
    shell: /home/pi/CubeSatSim/config -e
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to FUNcube"
    shell: /home/pi/CubeSatSim/config -j
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to Pacsat"
    shell: /home/pi/CubeSatSim/config -G
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Change Mode to Pacsat Ground Station"
    shell: /home/pi/CubeSatSim/config -I 
    icon: "&#128752;" # satellite
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Battery Saver Mode ON"
    shell: bash -c "/home/pi/CubeSatSim/config -B yes" 
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Battery Saver Mode OFF"
    shell: bash -c "/home/pi/CubeSatSim/config -B no" 
    icon: "&#10060;" # red X
    onclick: execution-dialog
    timeout: 5
 
  - title: "Turn Doppler Mode OFF"
    shell: /home/pi/CubeSatSim/config -K no 
    icon: "&#10060;" # red X
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Simulated Doppler Mode ON"
    shell: /home/pi/CubeSatSim/config -K sim
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5
 
  - title: "Turn Radio Control Doppler Mode ON"
    shell: /home/pi/CubeSatSim/config -K rig
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5

  - title: "Change TX and RX Frequency" 
    icon: "&#9881;" # gear
    shell: /home/pi/CubeSatSim/config -F {{ tx }} {{ rx }}
    onclick: execution-dialog
    timeout: 5
    arguments:
      - name: tx 
        type: ascii_sentence
      - name: rx 
        type: ascii_sentence

  - title: "Change Callsign" 
    icon: "&#9881;" # gear
    shell: /home/pi/CubeSatSim/config -c {{ callsign }}
    onclick: execution-dialog
    timeout: 5
    arguments:
      - name: callsign 
        type: ascii_sentence

  - title: "Change Latitude and Longitude" 
    icon: "&#9881;" # gear
    shell: /home/pi/CubeSatSim/config -l {{ lat }} {{ lon }}
    onclick: execution-dialog
    timeout: 5
    arguments:
      - name: lat
        type: ascii_sentence
      - name: lon 
        type: ascii_sentence

  - title: "Realtime CubeSatSim Log"
    shell: /home/pi/CubeSatSim/log -d r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "CubeSatSim Log"
    shell: /home/pi/CubeSatSim/log -d
    icon: logs
    onclick: execution-dialog
    timeout: 5

  - title: "Realtime Transmit Log"
    shell: /home/pi/CubeSatSim/log -t r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "Transmit Log"
    shell: /home/pi/CubeSatSim/log -t
    icon: logs
    onclick: execution-dialog
    timeout: 5
    
  - title: "Realtime Frequency Control Log"
    shell: /home/pi/CubeSatSim/log -r r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "Frequency Control Log"
    shell: /home/pi/CubeSatSim/log -r
    icon: logs
    onclick: execution-dialog
    timeout: 5

  - title: "Realtime Frequency Display Log"
    shell: /home/pi/CubeSatSim/log -f r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "Frequency Display Log"
    shell: /home/pi/CubeSatSim/log -f
    icon: logs
    onclick: execution-dialog
    timeout: 5

  - title: "Realtime Pacsat Log"
    shell: /home/pi/CubeSatSim/log -p r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "Pacsat Log"
    shell: /home/pi/CubeSatSim/log -p
    icon: logs
    onclick: execution-dialog
    timeout: 5    

  - title: "Realtime Pushbutton Log"
    shell: /home/pi/CubeSatSim/log -b r
    icon: logs
    onclick: execution-dialog
    timeout: 60
    
  - title: "Pushbutton Log"
    shell: /home/pi/CubeSatSim/log -b
    icon: logs
    onclick: execution-dialog
    timeout: 5    
    
  - title: "Realtime Command and Control Log"
    shell: /home/pi/CubeSatSim/log -c r
    icon: logs
    onclick: execution-dialog
    timeout: 60

  - title: "Command and Control Log"
    shell: /home/pi/CubeSatSim/log -c
    icon: logs
    onclick: execution-dialog
    timeout: 5

  - title: "Restart CubeSatSim"
    shell: echo "Restarting CubeSatSim now!" && sudo reboot now
    icon: restart
    onclick: execution-dialog
    timeout: 5

  - title: "Shutdown CubeSatSim"
    shell: echo "Shutting Down CubeSatSim now!" && sudo shutdown now
    icon: restart
    onclick: execution-dialog
    timeout: 5

  - title: "Restart CubeSatSim Software"
    shell: /home/pi/CubeSatSim/config -i
    icon: restart
    onclick: execution-dialog
    timeout: 5

  - title: "Scan I2C Bus"    
    shell: /home/pi/CubeSatSim/config -S
    icon: logs
    onclick: execution-dialog  
    timeout: 60
    
  - title: "Clear Logs and Restart"    
    shell: /home/pi/CubeSatSim/config -C
    icon: restart
    onclick: execution-dialog
    timeout: 5
    
  - title: "Read Squelch"    
    shell: /home/pi/CubeSatSim/config -Q
    icon: logs
    onclick: execution-dialog  
    timeout: 15

  - title: "Display Payload Sensor Data"    
    shell: /home/pi/CubeSatSim/config -p
    icon: logs
    onclick: execution-dialog  
    timeout: 15

  - title: "Display Voltage and Current Data"    
    shell: /home/pi/CubeSatSim/config -v
    icon: logs
    onclick: execution-dialog  
    timeout: 15

  - title: "Reset the Pacsat Configuration"
    icon: "&#9881;" # gear
    shell: /home/pi/CubeSatSim/config -k
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Simulated Telemetry ON"
    shell: /home/pi/CubeSatSim/config -t yes
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Simulated Telemetry OFF"
    shell: /home/pi/CubeSatSim/config -t no
    icon: "&#10060;" # red X
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Balloon Mode ON"
    shell: /home/pi/CubeSatSim/config -H yes
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Balloon Mode OFF"
    shell: /home/pi/CubeSatSim/config -H no
    icon: "&#10060;" # red X
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Command and Control ON"
    shell: /home/pi/CubeSatSim/config -T yes
    icon: "&#128994;" # green ball
    onclick: execution-dialog
    timeout: 5

  - title: "Turn Command and Control OFF"
    shell: /home/pi/CubeSatSim/config -T no
    icon: "&#10060;" # red X
    onclick: execution-dialog
    timeout: 5
    
dashboards:
  - title: CubeSatSim Dashboard
    contents:
      - title: Show Configuration
        contents:
          - title: "Show CubeSatSim Config"
      - title: Mode Changes
        contents:
          - title: "Change Mode to APRS"
          - title: "Change Mode to FSK"
          - title: "Change Mode to BPSK"
          - title: "Change Mode to SSTV"
          - title: "Change Mode to CW"
          - title: "Change Mode to FUNcube"
          - title: "Change Mode to Repeater"
          - title: "Change Mode to Pacsat"
          - title: "Change Mode to Pacsat Ground Station"
          
      - title: Settings
        contents:
          - title: "Change Callsign"
          - title: "Change Latitude and Longitude" 
          - title: "Change TX and RX Frequency" 
          - title: "Reset the Pacsat Configuration" 
          - title: "Turn Simulated Doppler Mode ON"
          - title: "Turn Radio Control Doppler Mode ON"
          - title: "Turn Doppler Mode OFF"
          - title: "Turn Command and Control ON"
          - title: "Turn Command and Control OFF"
          - title: "Turn Battery Saver Mode ON"
          - title: "Turn Battery Saver Mode OFF"
          - title: "Turn Simulated Telemetry ON"
          - title: "Turn Simulated Telemetry OFF"
          - title: "Turn Balloon Mode ON"
          - title: "Turn Balloon Mode OFF"
          
      - title: Logs
        contents:
          - title: Static Logs
            contents:        
              - title: "CubeSatSim Log"
              - title: "Transmit Log"
              - title: "Command and Control Log"
              - title: "Pacsat Log"
              - title: "Frequency Control Log"
              - title: "Frequency Display Log"
              - title: "Pushbutton Log"
              - title: "OliveTin Log"
          - title: Realtime Logs
            contents:        
              - title: "Realtime CubeSatSim Log"
              - title: "Realtime Transmit Log"
              - title: "Realtime Command and Control Log"
              - title: "Realtime Pacsat Log"
              - title: "Realtime Frequency Control Log"
              - title: "Realtime Frequency Display Log"
              - title: "Realtime Pushbutton Log"
              - title: "Realtime OliveTin Log"
              
      - title: Diagnostics
        contents:
          - title: "Scan I2C Bus"
          - title: "Read Squelch" 
          - title: "Display Payload Sensor Data"
          - title: "Display Voltage and Current Data" 
          
      - title: Restart and Shutdown
        contents:
          - title: "Restart CubeSatSim"
          - title: "Shutdown CubeSatSim"
          - title: "Restart CubeSatSim Software"
          - title: "Clear Logs and Restart" 

